language: php

php:
  - 7.0
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: nightly
    - php: hhvm

before_install:
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/http-kernel:$SYMFONY_VERSION symfony/dependency-injection:$SYMFONY_VERSION symfony/yaml:$SYMFONY_VERSION; fi

script:
  - bin/phpunit

after_script:
  - bin/coveralls

before_script:
  - composer install -n

script:
  - bin/phpspec run -fpretty --verbose
  - bin/phpunit

notifications:
  email:
    - system+travis-ci@hmlb.fr

env:
  - COMPOSER_PROCESS_TIMEOUT=1800
